import { CoreMetric, RawFinancialData } from '../types';

export const coreMetrics: CoreMetric[] = [
  {
    id: 'ticker',
    name: 'Ticker',
    category: 'Basic Information',
    format: 'text',
    calculate: (data) => data.ticker,
  },
  {
    id: 'name',
    name: 'Company Name',
    category: 'Basic Information',
    format: 'text',
    calculate: (data) => data.name,
  },
  {
    id: 'industry',
    name: 'Industry',
    category: 'Basic Information',
    format: 'text',
    calculate: (data) => data.industry || 'N/A',
  },
  {
    id: 'sector',
    name: 'Sector',
    category: 'Basic Information',
    format: 'text',
    calculate: (data) => data.sector || 'N/A',
  },
  {
    id: 'marketCap',
    name: 'Market Cap',
    category: 'Basic Information',
    format: 'currency',
    calculate: (data) => data.marketCap ?? null,
  },
  {
    id: 'price',
    name: 'Price',
    category: 'Basic Information',
    format: 'currency',
    calculate: (data) => data.price ?? null,
  },
  {
    id: 'peRatio',
    name: 'P/E Ratio',
    category: 'Valuation',
    format: 'ratio',
    calculate: (data) => data.peRatio ?? null,
  },
  {
    id: 'pbRatio',
    name: 'P/B Ratio',
    category: 'Valuation',
    format: 'ratio',
    calculate: (data) => data.pbRatio ?? null,
  },
  {
    id: 'psRatio',
    name: 'P/S Ratio',
    category: 'Valuation',
    format: 'ratio',
    calculate: (data) => data.psRatio ?? null,
  },
  {
    id: 'pegRatio',
    name: 'PEG Ratio',
    category: 'Valuation',
    format: 'ratio',
    calculate: (data) => data.pegRatio ?? null,
  },
  {
    id: 'evToEbitda',
    name: 'EV/EBITDA',
    category: 'Valuation',
    format: 'ratio',
    calculate: (data) => data.evToEbitda ?? null,
  },
  {
    id: 'grossMargin',
    name: 'Gross Margin',
    category: 'Profitability',
    format: 'percentage',
    calculate: (data) => data.grossMargin ?? null,
  },
  {
    id: 'operatingMargin',
    name: 'Operating Margin',
    category: 'Profitability',
    format: 'percentage',
    calculate: (data) => data.operatingMargin ?? null,
  },
  {
    id: 'netMargin',
    name: 'Net Margin',
    category: 'Profitability',
    format: 'percentage',
    calculate: (data) => data.netMargin ?? null,
  },
  {
    id: 'roe',
    name: 'ROE',
    category: 'Profitability',
    format: 'percentage',
    calculate: (data) => data.roe ?? null,
  },
  {
    id: 'roa',
    name: 'ROA',
    category: 'Profitability',
    format: 'percentage',
    calculate: (data) => data.roa ?? null,
  },
  {
    id: 'revenueQoQ',
    name: 'Revenue Growth (QoQ)',
    category: 'Growth',
    format: 'percentage',
    calculate: (data) => data.revenueQoQ ?? null,
  },
  {
    id: 'revenueYoY',
    name: 'Revenue Growth (YoY)',
    category: 'Growth',
    format: 'percentage',
    calculate: (data) => data.revenueYoY ?? null,
  },
  {
    id: 'revenue3Yr',
    name: 'Revenue Growth (3-Yr Avg)',
    category: 'Growth',
    format: 'percentage',
    calculate: (data) => data.revenue3Yr ?? null,
  },
  {
    id: 'revenue5Yr',
    name: 'Revenue Growth (5-Yr Avg)',
    category: 'Growth',
    format: 'percentage',
    calculate: (data) => data.revenue5Yr ?? null,
  },
  {
    id: 'epsGrowthYoY',
    name: 'EPS Growth (YoY)',
    category: 'Growth',
    format: 'percentage',
    calculate: (data) => data.epsGrowthYoY ?? null,
  },
  {
    id: 'epsGrowth3Yr',
    name: 'EPS Growth (3-Yr Avg)',
    category: 'Growth',
    format: 'percentage',
    calculate: (data) => data.epsGrowth3Yr ?? null,
  },
  {
    id: 'epsGrowth5Yr',
    name: 'EPS Growth (5-Yr Avg)',
    category: 'Growth',
    format: 'percentage',
    calculate: (data) => data.epsGrowth5Yr ?? null,
  },
  {
    id: 'currentRatio',
    name: 'Current Ratio',
    category: 'Financial Health',
    format: 'ratio',
    calculate: (data) => data.currentRatio ?? null,
  },
  {
    id: 'quickRatio',
    name: 'Quick Ratio',
    category: 'Financial Health',
    format: 'ratio',
    calculate: (data) => data.quickRatio ?? null,
  },
  {
    id: 'debtToEquity',
    name: 'Debt-to-Equity',
    category: 'Financial Health',
    format: 'ratio',
    calculate: (data) => data.debtToEquity ?? null,
  },
  {
    id: 'totalCash',
    name: 'Total Cash',
    category: 'Financial Health',
    format: 'currency',
    calculate: (data) => data.totalCash ?? null,
  },
  {
    id: 'dividendYield',
    name: 'Dividend Yield',
    category: 'Dividends',
    format: 'percentage',
    calculate: (data) => data.dividendYield ?? null,
  },
  {
    id: 'payoutRatio',
    name: 'Payout Ratio',
    category: 'Dividends',
    format: 'percentage',
    calculate: (data) => data.payoutRatio ?? null,
  },
];
