import { CoreMetric } from '../shared/types/types';

export const coreMetrics: CoreMetric[] = [
  // --- Basic Information ---
  {
    id: 'ticker',
    name: 'Ticker',
    category: 'Basic Information',
    format: 'text',
    calculate: (data) => data.ticker,
  },
  {
    id: 'name',
    name: 'Company Name',
    category: 'Basic Information',
    format: 'text',
    calculate: (data) => data.name,
  },
  {
    id: 'industry',
    name: 'Industry',
    category: 'Basic Information',
    format: 'text',
    calculate: (data) => data.industry ?? null,
  },
  {
    id: 'sector',
    name: 'Sector',
    category: 'Basic Information',
    format: 'text',
    calculate: (data) => data.sector ?? null,
  },
  {
    id: 'marketCap',
    name: 'Market Cap',
    category: 'Basic Information',
    format: 'currency',
    calculate: (data) => data.marketCap ?? null,
    aggregationMethod: 'sum',  
  },
  {
    id: 'price',
    name: 'Price',
    category: 'Basic Information',
    format: 'currency',
    calculate: (data) => data.price ?? null,
    aggregationMethod: 'weightedAverage',  
  },

  // --- Valuation ---
  {
    id: 'peRatio',
    name: 'P/E Ratio',
    category: 'Valuation',
    format: 'ratio',
    calculate: (data) => data.peRatio ?? null,
    aggregationMethod: 'weightedAverage',  
  },
  {
    id: 'pbRatio',
    name: 'P/B Ratio',
    category: 'Valuation',
    format: 'ratio',
    calculate: (data) => data.pbRatio ?? null,
    aggregationMethod: 'weightedAverage',  
  },
  {
    id: 'psRatio',
    name: 'P/S Ratio',
    category: 'Valuation',
    format: 'ratio',
    calculate: (data) => data.psRatio ?? null,
    aggregationMethod: 'weightedAverage',  
  },
  {
    id: 'pegRatio',
    name: 'PEG Ratio',
    category: 'Valuation',
    format: 'ratio',
    calculate: (data) => data.pegRatio ?? null,
    aggregationMethod: 'weightedAverage',  
  },
  {
    id: 'evToEbitda',
    name: 'EV/EBITDA',
    category: 'Valuation',
    format: 'ratio',
    calculate: (data) => data.evToEbitda ?? null,
    aggregationMethod: 'weightedAverage',  
  },

  // --- Profitability ---
  {
    id: 'grossMargin',
    name: 'Gross Margin',
    category: 'Profitability',
    format: 'percentage',
    calculate: (data) => data.grossMargin ?? null,
    aggregationMethod: 'weightedAverage',  
  },
  {
    id: 'operatingMargin',
    name: 'Operating Margin',
    category: 'Profitability',
    format: 'percentage',
    calculate: (data) => data.operatingMargin ?? null,
    aggregationMethod: 'weightedAverage',  
  },
  {
    id: 'netMargin',
    name: 'Net Margin',
    category: 'Profitability',
    format: 'percentage',
    calculate: (data) => data.netMargin ?? null,
    aggregationMethod: 'weightedAverage',  
  },
  {
    id: 'roe',
    name: 'ROE',
    category: 'Profitability',
    format: 'percentage',
    calculate: (data) => data.roe ?? null,
    aggregationMethod: 'weightedAverage',  
  },
  {
    id: 'roa',
    name: 'ROA',
    category: 'Profitability',
    format: 'percentage',
    calculate: (data) => data.roa ?? null,
    aggregationMethod: 'weightedAverage',  
  },

  // --- Growth ---
  {
    id: 'revenueQoQ',
    name: 'Revenue Growth (QoQ)',
    category: 'Growth',
    format: 'percentage',
    calculate: (data) => data.revenueQoQ ?? null,
    aggregationMethod: 'weightedAverage',  
  },
  {
    id: 'revenueYoY',
    name: 'Revenue Growth (YoY)',
    category: 'Growth',
    format: 'percentage',
    calculate: (data) => data.revenueYoY ?? null,
    aggregationMethod: 'weightedAverage',  
  },
  {
    id: 'revenue3Yr',
    name: 'Revenue Growth (3-Yr Avg)',
    category: 'Growth',
    format: 'percentage',
    calculate: (data) => data.revenue3Yr ?? null,
    aggregationMethod: 'weightedAverage',  
  },
  {
    id: 'revenue5Yr',
    name: 'Revenue Growth (5-Yr Avg)',
    category: 'Growth',
    format: 'percentage',
    calculate: (data) => data.revenue5Yr ?? null,
    aggregationMethod: 'weightedAverage',  
  },
  {
    id: 'epsGrowthYoY',
    name: 'EPS Growth (YoY)',
    category: 'Growth',
    format: 'percentage',
    calculate: (data) => data.epsGrowthYoY ?? null,
    aggregationMethod: 'weightedAverage',  
  },
  {
    id: 'epsGrowth3Yr',
    name: 'EPS Growth (3-Yr Avg)',
    category: 'Growth',
    format: 'percentage',
    calculate: (data) => data.epsGrowth3Yr ?? null,
    aggregationMethod: 'weightedAverage',  
  },
  {
    id: 'epsGrowth5Yr',
    name: 'EPS Growth (5-Yr Avg)',
    category: 'Growth',
    format: 'percentage',
    calculate: (data) => data.epsGrowth5Yr ?? null,
    aggregationMethod: 'weightedAverage',  
  },

  // --- Financial Health ---
  {
    id: 'currentRatio',
    name: 'Current Ratio',
    category: 'Financial Health',
    format: 'ratio',
    calculate: (data) => data.currentRatio ?? null,
    aggregationMethod: 'weightedAverage',  
  },
  {
    id: 'quickRatio',
    name: 'Quick Ratio',
    category: 'Financial Health',
    format: 'ratio',
    calculate: (data) => data.quickRatio ?? null,
    aggregationMethod: 'weightedAverage',  
  },
  {
    id: 'debtToEquity',
    name: 'Debt-to-Equity',
    category: 'Financial Health',
    format: 'ratio',
    calculate: (data) => data.debtToEquity ?? null,
    aggregationMethod: 'weightedAverage',  
  },
  {
    id: 'totalCash',
    name: 'Total Cash',
    category: 'Financial Health',
    format: 'currency',
    calculate: (data) => data.totalCash ?? null,
    aggregationMethod: 'sum',  
  },
  {
    id: 'totalDebt',
    name: 'Total Debt',
    category: 'Financial Health',
    format: 'currency',
    calculate: (data) => data.totalDebt ?? null,
    aggregationMethod: 'sum',  
  },

  // --- Dividends ---
  {
    id: 'dividendYield',
    name: 'Dividend Yield',
    category: 'Dividends',
    format: 'percentage',
    calculate: (data) => data.dividendYield ?? null,
    aggregationMethod: 'weightedAverage',  
  },
  {
    id: 'payoutRatio',
    name: 'Payout Ratio',
    category: 'Dividends',
    format: 'percentage',
    calculate: (data) => data.payoutRatio ?? null,
    aggregationMethod: 'weightedAverage',  
  },
    
  // --- Other Financial Data (for aggregation) ---
  // These are the raw numbers used to calculate other metrics
  {
    id: 'revenueTTM',
    name: 'Revenue (TTM)',
    category: 'Financials',
    format: 'currency',
    calculate: (data) => data.revenueTTM ?? null,
    aggregationMethod: 'sum',  
  },
  {
    id: 'netIncome',
    name: 'Net Income',
    category: 'Financials',
    format: 'currency',
    calculate: (data) => data.netIncome ?? null,
    aggregationMethod: 'sum',  
  },
  {
    id: 'eps',
    name: 'EPS',
    category: 'Financials',
    format: 'currency',
    calculate: (data) => data.eps ?? null,
    aggregationMethod: 'weightedAverage',  
  },
  {
    id: 'ebitda',
    name: 'EBITDA',
    category: 'Financials',
    format: 'currency',
    calculate: (data) => data.ebitda ?? null,
    aggregationMethod: 'sum',  
  },
  {
    id: 'enterpriseValue',
    name: 'Enterprise Value',
    category: 'Financials',
    format: 'currency',
    calculate: (data) => data.enterpriseValue ?? null,
    aggregationMethod: 'sum',  
  },
  {
    id: 'bookValue',
    name: 'Book Value',
    category: 'Financials',
    format: 'currency',
    calculate: (data) => data.bookValue ?? null,
    aggregationMethod: 'sum',  
  },
  {
    id: 'totalAssets',
    name: 'Total Assets',
    category: 'Financials',
    format: 'currency',
    calculate: (data) => data.totalAssets ?? null,
    aggregationMethod: 'sum',  
  },
  {
    id: 'totalEquity',
    name: 'Total Equity',
    category: 'Financials',
    format: 'currency',
    calculate: (data) => data.totalEquity ?? null,
    aggregationMethod: 'sum',  
  },
];
